### ISSUE TITLE
HTTP error 409 in ensure_workspace_security_roles during startup

### ISSUE THREAD

**Issue by jirik** [jirik/layman#108]
v1.7.0

During Layman startup, this log appeared in `layman` container:
```
[2020-09-30 13:57:03,767] INFO in __init__: Ensuring user <username>
[2020-09-30 13:57:03,767] INFO in util: ensure_whole_user:<username>
[2020-09-30 13:57:03,786] INFO in __init__: User <username> already exists
[2020-09-30 13:57:03 +0000] [13] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.6/dist-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.6/dist-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.6/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.6/dist-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.6/dist-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.6/dist-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/code/src/layman/__init__.py", line 80, in <module>
    ensure_whole_user(username)
  File "/code/src/layman/util.py", line 101, in ensure_whole_user
    call_modules_fn(providers, 'ensure_whole_user', [username])
  File "/code/src/layman/util.py", line 181, in call_modules_fn
    k: v for k, v in kwargs.items()
  File "/code/src/layman/common/geoserver/__init__.py", line 299, in ensure_whole_user
    ensure_user_workspace(username, auth)
  File "/code/src/layman/common/geoserver/__init__.py", line 261, in ensure_user_workspace
    ensure_workspace_security(username, 'r', auth)
  File "/code/src/layman/common/geoserver/__init__.py", line 171, in ensure_workspace_security
    ensure_workspace_security_roles(workspace, roles, type, auth)
  File "/code/src/layman/common/geoserver/__init__.py", line 157, in ensure_workspace_security_roles
    r.raise_for_status()
  File "/usr/local/lib/python3.6/dist-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: http://geoserver:8080/geoserver/rest/security/acl/layers/
[2020-09-30 13:57:03 +0000] [13] [INFO] Worker exiting (pid: 13)
[2020-09-30 13:57:03,807] INFO in __init__: Role USER_<username> already exists
[2020-09-30 13:57:03,826] INFO in __init__: Role USER_<username> already associated with user <username>
...
```

And after ensuring all users:
```
[2020-09-30 13:57:07 +0000] [12] [INFO] Worker exiting (pid: 12)
[2020-09-30 13:57:07 +0000] [1] [INFO] Shutting down: Master
[2020-09-30 13:57:07 +0000] [1] [INFO] Reason: Worker failed to boot.
```
leading to exit of the `layman` container.

The *worker* probably means Gunicorn process in this context, also because celery worker was still running after this crash.

After restart, the error did not appear again.

**Comment by index-git** [comment]
Stale
